

#ifndef FLAPPYBIRD_FLAPPYBIRD_SETTINGS_H
#define FLAPPYBIRD_FLAPPYBIRD_SETTINGS_H

#define BIRD_WIDTH 5
#define BIRD_HEIGHT 5
#define BIRD_HORIZONTAL_VELOCITY -50

#define BIRD_HP 3

#define BIRD_JUMP -35

#define BIRD_INITIAL_X 20
#define BIRD_INITIAL_Y 20
#define DIST_BETWEEN_BIRDS BIRD_WIDTH*2

#define PIPE_WIDTH 10
#define PIPE_HOLE_SIZE 25

#define GRAVITY 25

#endif //FLAPPYBIRD_FLAPPYBIRD_SETTINGS_H
