

#ifndef FLAPPYBIRD_FLAPPYBIRD_SETTINGS_H
#define FLAPPYBIRD_FLAPPYBIRD_SETTINGS_H

#include <timer_service.h>

#define GO_FACTORY_CREATE_EVERY_S 3

#define BIRD_COUNT 2
#define BIRD_WIDTH 5
#define BIRD_HEIGHT 5
#define BIRD_HORIZONTAL_VELOCITY -50

#define BIRD_JUMP -35

#define BIRD_INITIAL_X 10
#define BIRD_INITIAL_Y 10
#define DIST_BETWEEN_BIRDS BIRD_WIDTH*2

#define WALL_WIDTH 10
#define WALL_HOLE_HEIGHT 20

#define GRAVITY 50

#endif //FLAPPYBIRD_FLAPPYBIRD_SETTINGS_H
